alias(
  name = "uniffi",
  actual = "//3rdparty/uniffi-bin",
  visibility = ["//visibility:public"]
)

alias(
  name = "uniffi-swift",
  actual = "//3rdparty/uniffi-bin",
  visibility = ["//visibility:public"]
)
