alias(
  name = "uniffi",
  actual = "@bindeps//:uniffi__uniffi-bindgen",
  visibility = ["//visibility:public"]
)

alias(
  name = "uniffi-swift",
  actual = "@bindeps//:uniffi__uniffi-bindgen-swift",
  visibility = ["//visibility:public"]
)
